### ISSUE TITLE
Urban Flight?

### ISSUE THREAD

**Issue by destr02** [jacob404/promod#9]
I dont know how much you care about custom maps but if you ever have some time to look into urban flight, on map 3 it still has natural horde which is quite annoying :/

**Comment by destr02** [comment]
Also if some nerfs would be possible for the incredibly difficult finale they would be very appreciated. The map is very popular in the eu scene but this can sometimes ruin the fun completely.

**Comment by jacob404** [comment]
We've made quite a few tweaks to this map already, and I don't want to invest much more time into it. I can look into the natural hordes, but I don't want to brainstorm ideas for the finale because that will take away time from working on other things for pro mod. If you have any suggestions for the finale I will consider them however.

**Comment by destr02** [comment]
Well, i did have some in mind:

**Comment by destr02** [comment]
Well, i did have some in mind and asked around a bit for opinions, and it everything kinda comes down to this:
1. Reduce the horde a bit - sometimes feels like its really numerous, more than any other l4d(2) finale and it usually plays a big factor in teams wipe.
2. Either move the cans closer, inside the building (kinda like c1m2 cola i guess), or make it so that its easier to toss a can up the ledge near the door (not to be so high and hard, people always end up carrying cans around, up the catwalk), or maybe even reduce cans by few (not sure about this one).

**Comment by destr02** [comment]
Also would be nice if the cans were worth some points, so comebacks wouldn't be impossible.

**Comment by jacob404** [comment]
im no longer offering additional support to custom campaigns
